baseline: Coregraf de cuvinte
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: După ce citești un articol, ai să mă cunoști mai bine
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Sergiu A. Rus
baseurl: /
canonicalurl: true
