baseline: Adrian
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: Coregraf de cuvinte
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Sergiu
baseurl: https://www.sergiu-adrian.ro/
canonicalurl: false
